GET http://localhost:3000/api/users

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "teste",
    "email": "teste123@Upf.br"
}

### 
PUT http://localhost:3000/api/users/1
Content-Type: application/json

{
    "email": "teste1234@upf.br",
    "name": "teste alteracao"
}

###
DELETE http://localhost:3000/api/users/2

### Variáveis
@baseUrl = http://localhost:3000/api

### 1. Criar perfil (userId válido) -> deve retornar 201
POST {{baseUrl}}/profiles
Content-Type: application/json

{
  "userId": 1,
  "fullName": "teste123",
  "birthDate": "1990-01-15T00:00:00Z"
}

### 2. Criar segundo perfil pro MESMO userId -> deve retornar 409
POST {{baseUrl}}/profiles
Content-Type: application/json

{
  "userId": 1,
  "fullName": "abcd"
}

### 3. Criar perfil pra userId que NÃO existe -> deve retornar 400
POST {{baseUrl}}/profiles
Content-Type: application/json

{
  "userId": 9999,
  "fullName": "Usuário User"
}

### 4. Buscar perfil por id existente -> deve retornar 200
GET {{baseUrl}}/profiles/1

### 5. Buscar perfil por id que não existe -> deve retornar 404
GET {{baseUrl}}/profiles/9999

### 6. Atualizar perfil existente -> deve retornar 200
PUT {{baseUrl}}/profiles/1
Content-Type: application/json

{
  "fullName": "teste123 Atualizado"
}

### 7. Atualizar perfil que não existe -> deve retornar 404
PUT {{baseUrl}}/profiles/9999
Content-Type: application/json

{
  "fullName": "Não existe"
}

### 8. Validação: fullName vazio -> deve retornar 400
POST {{baseUrl}}/profiles
Content-Type: application/json

{
  "userId": 2,
  "fullName": ""
}