GET http://localhost:3000/api/users

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "teste",
    "email": "teste123@Upf.br"
}

### 
PUT http://localhost:3000/api/users/1
Content-Type: application/json

{
    "email": "teste1234@upf.br",
    "name": "teste alteracao"
}

###
DELETE http://localhost:3000/api/users/2

### Variáveis
@baseUrl = http://localhost:3000/api
